package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class CalendarTest extends LedgeWebTestCase 
{
    public void testComponent() throws Exception 
    {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("documents");
        assertActualView("BROWSING:/home_page/components/documents");

        clickLink("calendarEvents");
        assertActualView("BROWSING:/home_page/components/documents/calendarEvents");

        clickLinkWithText("Events calendar",1);
        assertActualView("BROWSING:/home_page/screens/documents/eventsCalendar");

        beginAt("/app/cms/x/708"); // TODO select correct link
        assertActualView("BROWSING:/home_page/screens/documents/eventsCalendar");

        beginAt("/app/cms/x/708?category_id_1=-1&category_id_2=-1&period=monthly&range=all&day=10&month=5&year=2005&B1=Zobacz&sort_field=event_start&sort_order=desc"); // TODO select correct link
        assertActualView("BROWSING:/home_page/screens/documents/eventsCalendar");
        assertLinkPresentWithText("Events calendar", 3);
        assertLinkNotPresentWithText("Events calendar", 4);
        
        beginAt("/app/cms/x/708?category_id_1=-1&category_id_2=-1&period=daily&range=all&day=10&month=5&year=2004&B1=Zobacz&sort_field=event_start&sort_order=desc"); // TODO select correct link
        assertActualView("BROWSING:/home_page/screens/documents/eventsCalendar");
        assertLinkPresentWithText("Events calendar",1);
        assertLinkNotPresentWithText("Events calendar", 2);
        
    }
}