package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class CategoriesTest extends LedgeWebTestCase 
{
    public void testCategoryQueryScreen() throws Exception 
    {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("screens");
        assertActualView("BROWSING:/home_page/screens");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/screens/categories");

        clickLink("categoryQueryResults");
        assertActualView("BROWSING:/home_page/screens/categories/categoryQueryResults");

        assertLinkPresentWithText("Category query list");
        assertLinkNotPresentWithText("Category query list", 1);
        assertLinkPresentWithText("Category query results", 2);
        assertLinkNotPresentWithText("Category query results", 3);
        assertLinkPresentWithText("Document resource list");
        assertLinkNotPresentWithText("Document resource list", 1);
        assertLinkPresentWithText("Holding resource list");
        assertLinkNotPresentWithText("Holding resource list", 1);
        assertLinkPresentWithText("Related resource list");
        assertLinkNotPresentWithText("Related resource list",1);
        assertLinkPresentWithText("Resource list");
        assertLinkNotPresentWithText("Resource list",1);
    }
    
    public void testCategoryQueryList() throws Exception {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/components/categories");

        clickLink("categoryQueryList");
        assertActualView("BROWSING:/home_page/components/categories/categoryQueryList");

        clickLinkWithText("query0");
        assertActualView("BROWSING:/home_page/screens/categories/categoryQueryResults");
    }

    public void testDocumentResourceList() throws Exception {
        beginAt("/"); // TODO select correct link
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/components/categories");

        clickLink("documentResourceList");
        assertActualView("BROWSING:/home_page/components/categories/documentResourceList");

        assertLinkPresentWithText("Category query list");
        assertLinkNotPresentWithText("Category query list", 1);
        assertLinkPresentWithText("Category query results");
        assertLinkNotPresentWithText("Category query results", 1);
        assertLinkPresentWithText("Document resource list",2);
        assertLinkNotPresentWithText("Document resource list", 3);
        assertLinkPresentWithText("Holding resource list");
        assertLinkNotPresentWithText("Holding resource list", 1);
        assertLinkPresentWithText("Related resource list");
        assertLinkNotPresentWithText("Related resource list",1);
        assertLinkPresentWithText("Resource list");
        assertLinkNotPresentWithText("Resource list",1);
    }

    public void testHoldingResourceList() throws Exception {
        beginAt("/"); // TODO select correct link
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/components/categories");

        clickLink("holdingResourceList");
        assertActualView("BROWSING:/home_page/components/categories/holdingResourceList");

        assertLinkPresentWithText("Category query list");
        assertLinkNotPresentWithText("Category query list", 1);
        assertLinkPresentWithText("Category query results");
        assertLinkNotPresentWithText("Category query results", 1);
        assertLinkPresentWithText("Document resource list");
        assertLinkNotPresentWithText("Document resource list", 1);
        assertLinkPresentWithText("Holding resource list",2);
        assertLinkNotPresentWithText("Holding resource list", 3);
        assertLinkPresentWithText("Related resource list");
        assertLinkNotPresentWithText("Related resource list",1);
        assertLinkPresentWithText("Resource list");
        assertLinkNotPresentWithText("Resource list",1);
    }

    public void testRelatedResourceList() throws Exception {
        beginAt("/"); // TODO select correct link
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/components/categories");

        clickLink("relatedResourceList");
        assertActualView("BROWSING:/home_page/components/categories/relatedResourceList");

        assertLinkPresentWithText("Category query list");
        assertLinkNotPresentWithText("Category query list", 1);
        assertLinkPresentWithText("Category query results");
        assertLinkNotPresentWithText("Category query results", 1);
        assertLinkPresentWithText("Document resource list");
        assertLinkNotPresentWithText("Document resource list", 1);
        assertLinkPresentWithText("Holding resource list");
        assertLinkNotPresentWithText("Holding resource list", 1);
        assertLinkPresentWithText("Related resource list",1);
        assertLinkNotPresentWithText("Related resource list",2);
        assertLinkPresentWithText("Resource list");
        assertLinkNotPresentWithText("Resource list",1);
    }

    public void testResourceList() throws Exception {
        beginAt("/"); // TODO select correct link
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("categories");
        assertActualView("BROWSING:/home_page/components/categories");

        clickLink("resourceList");
        assertActualView("BROWSING:/home_page/components/categories/resourceList");

        assertLinkPresentWithText("Category query list");
        assertLinkNotPresentWithText("Category query list", 1);
        assertLinkPresentWithText("Category query results");
        assertLinkNotPresentWithText("Category query results", 1);
        assertLinkPresentWithText("Document resource list");
        assertLinkNotPresentWithText("Document resource list", 1);
        assertLinkPresentWithText("Holding resource list");
        assertLinkNotPresentWithText("Holding resource list", 1);
        assertLinkPresentWithText("Related resource list");
        assertLinkNotPresentWithText("Related resource list",1);
        assertLinkPresentWithText("Resource list",2);
        assertLinkNotPresentWithText("Resource list",3);
    }
}