package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.DOMTreeWalker;
import org.objectledge.web.test.LedgeWebTestCase;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

public class ForumTest extends LedgeWebTestCase 
{
    public void testScenario1() throws Exception {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");
    
        clickLink("components");
        assertActualView("BROWSING:/home_page/components");
    
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
    
        clickLink("recentlyAddedMessages");
        assertActualView("BROWSING:/home_page/components/forum/recentlyAddedMessages");
    
        Element el = getTableWithText("Ostatnio dodane wiadomo");
        int rowsBefore = DOMTreeWalker.countElements(el, "tr");
        
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
        
        clickLink("forumComponent");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        clickLinkWithText("forum0");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        clickLinkWithText("Nowa wiadomość");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        setWorkingForm("component_under_test_forum_add_message");
        setFormElement("did", "770");
        setFormElement("content", "content1");
        setFormElement("priority", "2");
        setFormElement("name", "test1");
        setFormElement("parent", "770");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
        assertActionResult("added_successfully");
        rowsBefore++;
        
        clickLinkWithText("test1");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        clickLinkWithText("Odpowiedź");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        setWorkingForm("component_under_test_forum_add_message");
        setFormElement("did", "770");
        setFormElement("content", ">On 12:43 06.05.2005   root  wrote: >content1 content2");
        setFormElement("priority", "2");
        setFormElement("name", "test2");
        setFormElement("parent", "788");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
        assertActionResult("added_successfully");
        rowsBefore++;
        
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
    
        clickLink("recentlyAddedMessages");
        assertActualView("BROWSING:/home_page/components/forum/recentlyAddedMessages");
        
        Document doc = getTester().getDialog().getResponse().getDOM();
        DOMTreeWalker walker = new DOMTreeWalker(doc.getDocumentElement());
        el = getTableWithText(walker, "Ostatnio dodane wiadomo");
        int rowsAfter = DOMTreeWalker.countElements(el, "tr");
        if(rowsBefore > 13)
        {
            // table has only 10 places for last comments 
            rowsBefore = 13;
        }
        System.out.println("B: "+rowsBefore+":"+rowsAfter);
        assertEquals(rowsBefore, rowsAfter);
        String lastAdded = getTableRowText(walker, el, 2, 0);
        String beforeLastAdded = getTableRowText(walker, el, 3, 0);
        assertEquals("test2",lastAdded);
        assertEquals("test1",beforeLastAdded);
        
        
        // ^^^ insert new recordings here (do not remove) ^^^
    }
}