package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.DOMTreeWalker;
import org.objectledge.web.test.LedgeWebTestCase;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.meterware.httpunit.WebLink;

public class ForumTest extends LedgeWebTestCase 
{
    public void testComponents() throws Exception {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");
    
        clickLink("components");
        assertActualView("BROWSING:/home_page/components");
    
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
    
        clickLink("recentlyAddedMessages");
        assertActualView("BROWSING:/home_page/components/forum/recentlyAddedMessages");
    
        Element el = getTableWithText("Ostatnio dodane wiadomo");
		if(el == null)
		{
			el = getTableWithText("Messages added lately");
		}
        int rowsBefore = DOMTreeWalker.countElements(el, "tr");
        
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
        
        clickLink("forumComponent");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        clickLinkWithText("forum0");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        setWorkingForm("component_under_test_forum_add_message");
        setFormElement("did", "770");
        setFormElement("content", "content1");
        setFormElement("priority", "2");
        setFormElement("name", "test1");
        setFormElement("parent", "770");
		
		if(getDialog().isLinkPresentWithText("Wyślij"))
		{
			clickLinkWithText("Wyślij");
		}
		else
		{
			clickLinkWithText("Send");
		}
		
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
        assertActionResult("added_successfully");
        rowsBefore++;
        
        clickLinkWithText("test1");
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
		if(getDialog().isLinkPresentWithText("Odpowiedź"))
		{
	        clickLinkWithText("Odpowiedź");
		}
		else
		{
	        clickLinkWithText("Reply");
		}
        assertActualView("BROWSING:/home_page/components/forum/forumComponent");
    
        setWorkingForm("component_under_test_forum_add_message");
        setFormElement("did", "770");
        setFormElement("content", ">On 12:43 06.05.2005   root  wrote: >content1 content2");
        setFormElement("priority", "2");
        setFormElement("name", "test2");
		if(getDialog().isLinkPresentWithText("Wyślij"))
		{
			clickLinkWithText("Wyślij");
		}
		else
		{
			clickLinkWithText("Send");
		}
		assertActualView("BROWSING:/home_page/components/forum/forumComponent");
        assertActionResult("added_successfully");
        rowsBefore++;
        
        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");
    
        clickLink("recentlyAddedMessages");
        assertActualView("BROWSING:/home_page/components/forum/recentlyAddedMessages");
        
        Document doc = getTester().getDialog().getResponse().getDOM();
        DOMTreeWalker walker = new DOMTreeWalker(doc.getDocumentElement());
        el = getTableWithText(walker, "Ostatnio dodane wiadomo");
		if(el == null)
		{
			walker.reset();
			el = getTableWithText(walker, "Messages added lately");
		}
        int rowsAfter = DOMTreeWalker.countElements(el, "tr");
        if(rowsBefore > 13)
        {
            // table has only 10 places for last comments 
            rowsBefore = 13;
        }
        assertEquals(rowsBefore, rowsAfter);
        String lastAdded = getTableRowText(walker, el, 2, 0);
        String beforeLastAdded = getTableRowText(walker, el, 3, 0);
        assertEquals("test2",lastAdded);
        assertEquals("test1",beforeLastAdded);
        
        
        // ^^^ insert new recordings here (do not remove) ^^^
    }
    
    public void testForumScreen() throws Exception 
    {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("screens");
        assertActualView("BROWSING:/home_page/screens");

        clickLink("forum");
        assertActualView("BROWSING:/home_page/screens/forum");

        clickLink("forum");
        assertActualView("BROWSING:/home_page/screens/forum/forum");

        clickLinkWithText("forum0");
        assertActualView("BROWSING:/home_page/screens/forum/forum");

        clickLinkWithText("test message");
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Zaniechaj"))
		{
	        clickLinkWithText("Zaniechaj");
		}
		else
		{
			clickLinkWithText("Cancel");
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

        clickLinkWithText("test message");
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Odpowiedź"))
		{
	        clickLinkWithText("Odpowiedź");
		}
		else
		{
			WebLink link = getLinkWithURL("mid=771&state=NewMessage");
			link.click();
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Zaniechaj"))
		{
	        clickLinkWithText("Zaniechaj");
		}
		else
		{
			clickLinkWithText("Cancel");
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Powrót do listy wiadomości"))
		{
			clickLinkWithText("Powrót do listy wiadomości");
		}
		else
		{
			clickLinkWithText("Back to message list");
		}
        
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Powrót do listy dyskusji"))
		{
			clickLinkWithText("Powrót do listy dyskusji");
		}
		else
		{
			clickLinkWithText("Back to discussion list");
		}
        
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("dokument /home_page/components/forum/comments"))
		{
			clickLinkWithText("dokument /home_page/components/forum/comments");
		}
		else
		{
			clickLinkWithText("document /home_page/components/forum/comments");
		}
        
		
        assertActualView("BROWSING:/home_page/screens/forum/forum");

        clickLinkWithText("test comment");
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Powrót do listy wiadomości"))
		{
			clickLinkWithText("Powrót do listy wiadomości");
		}
		else
		{
			clickLinkWithText("Back to message list");
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/screens/forum/forum");

        setFormElement("did", "773");
        setFormElement("content", "xyz");
        setFormElement("priority", "2");
        setFormElement("name", "abc");
        setFormElement("parent", "773");
		if(getDialog().isLinkPresentWithText("Wyślij"))
		{
			clickLinkWithText("Wyślij");
		}
		else
		{
			clickLinkWithText("Send");
		}
		assertActualView("BROWSING:/home_page/screens/forum/forum");
        assertActionResult("added_successfully");

		if(getDialog().isLinkPresentWithText("Powrót do listy dyskusji"))
		{
			clickLinkWithText("Powrót do listy dyskusji");
		}
		else
		{
			clickLinkWithText("Back to discussion list");
		}
		assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("dokument /home_page/components/forum/comments"))
		{
			clickLinkWithText("dokument /home_page/components/forum/comments");
		}
		else
		{
			clickLinkWithText("document /home_page/components/forum/comments");
		}
		assertActualView("BROWSING:/home_page/screens/forum/forum");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
		assertActualView("BROWSING:/home_page/screens/forum/forum");

        setFormElement("did", "773");
        setFormElement("content", "");
        setFormElement("priority", "2");
        setFormElement("name", "");
        setFormElement("parent", "773");
		if(getDialog().isLinkPresentWithText("Wyślij"))
		{
			clickLinkWithText("Wyślij");
		}
		else
		{
			clickLinkWithText("Send");
		}
		assertActualView("BROWSING:/home_page/screens/forum/forum");
        assertActionResult("illegal_message_name");
        // ^^^ insert new recordings here (do not remove) ^^^
    }
    
    public void testCommentsComponent() throws Exception 
    {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("forum");
        assertActualView("BROWSING:/home_page/components/forum");

        clickLink("comments");
        assertActualView("BROWSING:/home_page/components/forum/comments");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/components/forum/comments");

        setFormElement("did", "773");
        setFormElement("content", "abcd");
        setFormElement("priority", "2");
        setFormElement("name", "abcd");
        setFormElement("parent", "773");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("added_successfully");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/components/forum/comments");

        setFormElement("did", "773");
        setFormElement("content", "");
        setFormElement("priority", "2");
        setFormElement("name", "");
        setFormElement("parent", "773");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("illegal_message_name");

        clickLinkWithText("test comment");
        assertActualView("BROWSING:/home_page/components/forum/comments");

		if(getDialog().isLinkPresentWithText("Nowa wiadomość"))
		{
			clickLinkWithText("Nowa wiadomość");
		}
		else
		{
			clickLinkWithText("New message");
		}
        assertActualView("BROWSING:/home_page/components/forum/comments");

        setFormElement("did", "773");
        setFormElement("content", "abcd");
        setFormElement("priority", "2");
        setFormElement("name", "abcd");
        setFormElement("parent", "773");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("added_successfully");

        clickLinkWithText("test comment");
        assertActualView("BROWSING:/home_page/components/forum/comments");

		if(getDialog().isLinkPresentWithText("Odpowiedź"))
		{
	        clickLinkWithText("Odpowiedź");
		}
		else
		{
			WebLink link = getLinkWithURL("mid=774&state=am");
			link.click();
	        //clickLinkWithText("Reply");
		}
		assertActualView("BROWSING:/home_page/components/forum/comments");

        setFormElement("did", "773");
        setFormElement("content", ">On 16:56 27.04.2005 root wrote: ");
        setFormElement("priority", "2");
        setFormElement("name", "abcd");
        setFormElement("parent", "774");
        clickLinkWithText("Wyślij");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("added_successfully");

        clickLinkWithText("widok listy");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("");

        clickLinkWithText("widok drzewa");
        assertActualView("BROWSING:/home_page/components/forum/comments");
        assertActionResult("");

        // ^^^ insert new recordings here (do not remove) ^^^
    }
    
}