package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class LinkCollectionTest extends LedgeWebTestCase {

    public void testScenario1() throws Exception {
        beginAt("/");
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("links");
        assertActualView("BROWSING:/home_page/components/links");

        clickLink("linkCollection");
        assertActualView("BROWSING:/home_page/components/links/linkCollection");
        assertLinkPresentWithText("ledge_link");
        assertLinkPresentWithText("caltha.pl");
        // ^^^ insert new recordings here (do not remove) ^^^
    }
}
