package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class PeriodicalTest extends LedgeWebTestCase 
{
    public void testBulletins() throws Exception {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("periodicals");
        assertActualView("BROWSING:/home_page/components/periodicals");

        clickLink("bulletins");
        assertActualView("BROWSING:/home_page/components/periodicals/bulletins");
      
        
        clickLinkWithText("bulletin0");
        assertActualView("BROWSING:/home_page/components/periodicals/bulletins");
        assertTextPresent("2005");
        assertTextNotPresent("Kwiecie");
        
        clickLinkWithImage("Lplus.gif");
        assertActualView("BROWSING:/home_page/components/periodicals/bulletins");
        assertActionResult("");
        assertTextPresent("Kwiecie");
        assertTextNotPresent("27.04.2005");

        clickLinkWithImage("Tplus.gif");
        assertActualView("BROWSING:/home_page/components/periodicals/bulletins");
        assertTextPresent("27.04.2005");
        
        assertActionResult("");
        
        //System.out.println(getDialog().getResponseText());
    }

    public void testPeriodicals() throws Exception {
        beginAt("/"); // TODO select correct link
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("periodicals");
        assertActualView("BROWSING:/home_page/components/periodicals");

        clickLink("periodicalsComponent");
        assertActualView("BROWSING:/home_page/components/periodicals/periodicalsComponent");

        clickLinkWithImage("Lplus.gif");
        assertActualView("BROWSING:/home_page/components/periodicals/periodicalsComponent");
        assertActionResult("");
        assertTextPresent("Kwiecie");
        assertTextNotPresent("27.04.2005");
        
        clickLinkWithImage("Tplus.gif");
        assertActualView("BROWSING:/home_page/components/periodicals/periodicalsComponent");
        assertActionResult("");
        assertTextPresent("27.04.2005");

        // ^^^ insert new recordings here (do not remove) ^^^
    }
}