package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class RelatedResourcesTest extends LedgeWebTestCase {

    public void testScenario1() throws Exception {
        beginAt("/"); 
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("resourceRelations");
        assertActualView("BROWSING:/home_page/components/resourceRelations");

        clickLink("relatedResourcesList");
        assertActualView("BROWSING:/home_page/components/resourceRelations/relatedResourcesList");
        assertLinkPresentWithText("caltha-logo.gif");
        // ^^^ insert new recordings here (do not remove) ^^^
    }
}
