package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class RepositoryViewTest extends LedgeWebTestCase {

    public void testScenario1() throws Exception {
        beginAt("/");
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("fileRepository");
        assertActualView("BROWSING:/home_page/components/fileRepository");

        clickLink("repositoryView");
        assertActualView("BROWSING:/home_page/components/fileRepository/repositoryView");

        clickLinkWithText("protected");
        assertActualView("BROWSING:/home_page/components/fileRepository/repositoryView");
        assertLinkPresentWithText("plama.bmp");
        assertLinkPresentWithText("test");
        assertLinkPresentWithText("..");
		
		if(getDialog().isLinkPresentWithText("Katalog główny"))
		{
			clickLinkWithText("Katalog główny");
		}
		else
		{
			clickLinkWithText("Main directory");
		}
        // clickLinkWithText("..");
        assertActualView("BROWSING:/home_page/components/fileRepository/repositoryView");
        assertLinkPresentWithText("public");
        assertLinkPresentWithText("protected");
        assertLinkNotPresentWithText("..");
        assertLinkNotPresentWithText("Katalog główny");
		assertLinkNotPresentWithText("Main directory");

        clickLinkWithText("public");
        assertActualView("BROWSING:/home_page/components/fileRepository/repositoryView");
        assertLinkPresentWithText("bulletins");
        assertLinkPresentWithText("caltha-logo.gif");
        assertLinkPresentWithText("periodicals");
        assertLinkPresentWithText("..");

        // ^^^ insert new recordings here (do not remove) ^^^
    }
}
