package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class SearchBoxTest extends LedgeWebTestCase {

    public void testSearchBoxKeyword() throws Exception {
        beginAt("/");
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("searchEngine");
        assertActualView("BROWSING:/home_page/components/searchEngine");

        clickLink("searchInSite");
        assertActualView("BROWSING:/home_page/components/searchEngine/searchInSite");

        // WARN: Since search forms pass parameters as GET parameters (in the link) the following
        //       code is hand crafted 
        setFormElement("query", "list");
        clickLinkWithText("szukaj"); // TODO: maybe only 'szukaj' should be clicked

        assertActualView("BROWSING:/home_page/screens/searchEngine/searchResults");
        assertLinkPresentWithText("Wyszukiwanie zaawansowane");
        assertLinkPresentWithText("List navigation");
        assertLinkPresentWithText("Resource list");
        assertLinkPresentWithText("Related resources list");
        assertLinkPresentWithText("Category query list");
        assertLinkPresentWithText("Related resource list");
        assertLinkPresentWithText("Holding resource list");
        assertLinkPresentWithText("Document resource list");
        // ^^^ insert new recordings here (do not remove) ^^^
    }
    
    public void testAdvancedSearch() throws Exception {
        beginAt("/");
        assertActualView("BROWSING:/home_page");

        clickLink("screens");
        assertActualView("BROWSING:/home_page/screens");

        clickLink("searchEngine");
        assertActualView("BROWSING:/home_page/screens/searchEngine");

        clickLink("searchResults");
        assertActualView("BROWSING:/home_page/screens/searchEngine/searchResults");

        // WARN: Since search forms pass parameters as GET parameters (in the link) the following
        //       code is hand crafted 
        setFormElement("q_and", "list resource");
        setFormElement("q_expr", "");
        setFormElement("q_or", "holding");
        setFormElement("q_not", "document");
        setFormElement("res_num", "10");
        setFormElement("field", "index_title");
        setFormElement("q_time", "all");
        submit("go");

        assertActualView("BROWSING:/home_page/screens/searchEngine/searchResults");
        // TODO: Fix query after fixing http://objectledge.org/jira/browse/CYKLO-258
        assertFormElementEquals("query", "+((index_title:list index_title:resource)) (index_title:holding) -(index_title:document)");
        assertLinkPresentWithText("Wyszukiwanie zaawansowane");
        assertLinkPresentWithText("Holding resource list");
        assertLinkPresentWithText("Resource list");
        assertLinkPresentWithText("Related resource list");
        assertLinkPresentWithText("List navigation");
        

        // ^^^ insert new recordings here (do not remove) ^^^
    }    
}
