package org.cyklotron.components;
// generated by MaxQ [ com.bitmechanic.maxq.generator.TemplateCodeGenerator ]

import org.objectledge.web.test.LedgeWebTestCase;

public class SearchBoxTest extends LedgeWebTestCase {

    public void searchBoxKeyword() throws Exception {
        beginAt("/");
        assertActualView("BROWSING:/home_page");

        clickLink("components");
        assertActualView("BROWSING:/home_page/components");

        clickLink("searchEngine");
        assertActualView("BROWSING:/home_page/components/searchEngine");

        clickLink("searchInSite");
        assertActualView("BROWSING:/home_page/components/searchEngine/searchInSite");

        // WARN: Since search forms pass parameters as GET parameters (in the link) the following
        //       code is hand crafted, it will also work like this for Advanced Search 
        setFormElement("query", "list");
        clickLinkWithText("&raquo; szukaj"); // TODO: maybe only 'szukaj' should be clicked

        assertActualView("BROWSING:/home_page/screens/searchEngine/searchResults");
        assertLinkPresentWithText("Wyszukiwanie zaawansowane");
        assertLinkPresentWithText("List navigation");
        assertLinkPresentWithText("Resource list");
        assertLinkPresentWithText("Related resources list");
        assertLinkPresentWithText("Category query list");
        assertLinkPresentWithText("Related resource list");
        assertLinkPresentWithText("Holding resource list");
        assertLinkPresentWithText("Document resource list");
        // ^^^ insert new recordings here (do not remove) ^^^
    }
}
