package net.cyklotron.cms.catalogue;

public enum Problem
{
    INVALID_CLASS,
    INVALID_METADATA,
    MISSING_PROPERTIES,
    MISSING_DESCRIPTION_DOC,
    MULTIPLE_DESCRIPTION_DOCS,
    REQUIRED_CATEGORY_MISSING,
    DOCUMENT_NOT_ACCESSIBLE,
    FILE_NOT_ACCESSIBLE
}
